= External Workspace Manager Plugin @ GSoC 2016

Organization: link:https://jenkins.io/[Jenkins Project]

Student: link:https://github.com/alexsomai[Alexandru Somai]

Mentors: link:https://github.com/oleg-nenashev[Oleg Nenashev], link:https://github.com/martinda[Martin d'Anjou]

== Table of contents

. <<main-project,Main project - External Workspace Manager Plugin>>
. <<blog-posts,Blog posts @ jenkins.io>>
. <<related-projects,Related projects>>
.. <<run-selector-plugin,Run Selector Plugin>>
.. <<workspace-cleanup-plugin,Workspace Cleanup Plugin>>

== [[main-project]]Main project - External Workspace Manager Plugin

The main project that I have worked on during link:https://summerofcode.withgoogle.com/[Google Summer of Code] 2016
is called External Workspace Manager Plugin.
The complete documentation that I have written may be found
link:https://github.com/jenkinsci/external-workspace-manager-plugin/blob/master/README.md[here].

During the community bonding period I have created a plugin design document.
The document was also updated on the go, as I was progressing with the code.
It is publicly shared via Google Docs: https://docs.google.com/document/d/1yiisnsR7qg3XEEvch8vocWbitSUCZcoQ-pfzEVFg1eA/edit?usp=sharing

I have tracked my progress using JIRA.
The EPICs are:

* Coding period phase 1: link:https://issues.jenkins-ci.org/browse/JENKINS-35019[JENKINS-35019]
* Coding period phase 2: link:https://issues.jenkins-ci.org/browse/JENKINS-35971[JENKINS-35971]

The plugin's source code is on link:https://github.com/jenkinsci/external-workspace-manager-plugin[GitHub].
Following are the links to the list of **commits** I have made on this project:

* Page 1: https://github.com/jenkinsci/external-workspace-manager-plugin/commits/master?author=alexsomai&page=1
* Page 2: https://github.com/jenkinsci/external-workspace-manager-plugin/commits/master?author=alexsomai&page=2
* Page 3: https://github.com/jenkinsci/external-workspace-manager-plugin/commits/master?author=alexsomai&page=3

== [[blog-posts]]Blog posts @ jenkins.io

During the GSoC I have also submitted several blog posts on the Jenkins blogging page:

* The introductory blog post: https://jenkins.io/blog/2016/05/23/external-workspace-manager-plugin/
* The blog post announcing the alpha release: https://jenkins.io/blog/2016/06/30/ewm-alpha-version/

The blog posts were submitted via pull request: link:https://github.com/jenkins-infra/jenkins.io/pull/254[#254],
link:https://github.com/jenkins-infra/jenkins.io/pull/296[#296].
I have also made some other minor **contributions** to the
link:https://github.com/jenkins-infra/jenkins.io[jenkins.io] repository:

* https://github.com/jenkins-infra/jenkins.io/commits/master?author=alexsomai

== [[related-projects]]Related projects

My project is dependant, more or less, on other plugins.
Therefore, I have contributed to other Jenkins plugins too.

=== [[run-selector-plugin]]Run Selector Plugin

In the External Workspace Manager Plugin I needed a feature to select a specific build based on some input parameters.
Such feature was available in the link:https://github.com/jenkinsci/copyartifact-plugin[Copy Artifact Plugin].
But, my mentors and I have decided that it would be better for the community to isolate the build selection logic
in a separate plugin, so that, in the future other plugins may benefit from this functionality.
I have started a discussion about this on the Jenkins dev ML:
https://groups.google.com/forum/#!topic/jenkinsci-dev/G-ZnJu3h67g.

The work I did to decouple the build selection logic is in the
link:https://github.com/jenkinsci/run-selector-plugin[Run Selector Plugin].
The **commits** are:

* Page 1: https://github.com/jenkinsci/run-selector-plugin/commits/master?author=alexsomai&page=1
* Page 2: https://github.com/jenkinsci/run-selector-plugin/commits/master?author=alexsomai&page=2

// TODO - not released yet, but hopefully it will be
// I have also released the Run Selector Plugin.
// Minimum version 1.0 is needed to be used by the External Workspace Manager Plugin.

=== [[workspace-cleanup-plugin]]Workspace Cleanup Plugin

The External Workspace Manager Plugin needed a workspace cleanup feature, so that the user may automatically delete
the workspace after it was used.
The link:https://github.com/jenkinsci/ws-cleanup-plugin[Workspace Cleanup Plugin] does that,
but it was not Pipeline compatible.
Since my project is mainly focused on Pipeline jobs, I had to make the Workspace Cleanup Plugin to be
Pipeline compatible.
There was an existing issue related to that, too:
link:https://issues.jenkins-ci.org/browse/JENKINS-28454[JENKINS-28454].
The Pipeline compatibility pull request
link:https://github.com/jenkinsci/ws-cleanup-plugin/pull/27[#27] that I submitted was merged, and the afferent
**commits** are:

* https://github.com/jenkinsci/ws-cleanup-plugin/commits/master?author=alexsomai

The Workspace Cleanup Plugin was released with my changes.
Since version 0.30 it is compatible with my project, External Workspace Manager Plugin.
